---
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
  deploy_infra:
    jobs:
      - terraform/init:
          checkout: true
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/init
      - terraform/apply:
          attach-workspace: true
          context: terraform
          filters:
            branches:
              only: main
          requires:
            - terraform/plan